name: Docker Image CI

on:
  push:
    branches:
      - "main"
  schedule:
    - cron:  '0 */6 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ayes-web/breezewiki

jobs:
  build-push:

    runs-on: ubuntu-latest

    steps:
      # arm64 specific
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@4
        with:
          file: Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: ghcr.io/ayes-web/breezewiki:latest
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
